### ISSUE TITLE
Rationalize configuration properties

### ISSUE THREAD

**Issue by snicoll** [persapiens/jsf-spring-boot-starter#22]
I had a quick look at the code and I can see a lot of different prefixes for the configuration. A few thoughts:

* Maybe it would be nicer if all options were gathered under a common prefix (something like `jsf` if that makes sense?)
* If splitting the configuration by components is a good thing, maybe we should use the name of the component rather than a package name. This is a bit unusual compared to other libraries.

What do you think?

**Comment by persapiens** [comment]
Current implementation uses the components (jsf api, mojarra, primefaces and omnifaces) context-param attributes, because it could help migration between traditional web.xml configuration to spring boot.

However, I agree that all of these properties should follow the same **jsf** namespace, creating subdomains for each component when necessary. The configuration of components should use the name of each component also.

So, jsf namespace should be:

- **jsf** to standard jsf properties instead of javax.faces. For example javax.faces.PROJECT_STATE should be **jsf.PROJECT_STATE**
- **jsf.mojarra** to mojarra properties instead of com.sun.faces.
- **jsf.omnifaces** to omnifaces properties instead of omnifaces.
- **jsf.primefaces** to primefaces properties instead of primefaces. For example, primefaces.THEME should be **jsf.primefaces.THEME**

More helpful suggestions @snicoll ?

**Comment by snicoll** [comment]
@persapiens apologies for the delay, I was quite busy this week. The change looks good to me, thanks!
