### ISSUE TITLE
Annotated classes like @FacesConverter are not being registered

### ISSUE THREAD

**Issue by didiez** [persapiens/jsf-spring-boot-starter#66]
Simply starting the jsf-spring-boot-starter-example using one of the omnifaces converters, the application throws an error.

````
<p:selectOneMenu value="#{helloWorldMBean.nickname}"
                 converter="omnifaces.SelectItemsIndexConverter">
</p:selectOneMenu>
````

It seems to me that it's not scanning any annotated converter, validator, component, etc.
````
com.sun.faces.config.DelegatingAnnotationProvider.createAnnotatedMap(DelegatingAnnotationProvider.java:113)
````

**Comment by persapiens** [comment]
It think this error is related to the way jsf-spring-boot-starter **initializes** mojarra and myfaces.

On the **onStartup** method, both **FacesInitializer** (mojarra) and **MyFacesContainerInitializer** (myfaces) should receive the **set of classes that uses the types** described at HandlesTypes annotation usage, but these initialization classes receive **set of the types described** at HandlesTypes annotation usage.

This error happens with mojarra implementation, not with myfaces. I think it happens because mojarra uses the set of classes with problem intensively.

I'll push one branch with a proposed solution tomorrow.

**Comment by persapiens** [comment]
Hello @didiez , I've just pushed proposed implementation for initializing **FacesInitializer** (mojarra), **MyfacesContainerInitializer** (myfaces) and **FacesViewsInitializer** (omnifaces) properly at [**jsfInitializer branch**](https://github.com/persapiens/jsf-spring-boot-starter/tree/jsfInitializer).

@ronmamo [reflections](https://github.com/ronmamo/reflections) library is used to search classes. It is configured to scan classes in mojarra, myfaces and other libraries with META-INF/faces-config.xml.

Could you give a try?

Thanks in advance.

**Comment by didiez** [comment]
Whoa, that was fast.
I've already tried the modified branch and works like a charm.
Thanks @persapiens for your awesome job, I'll contribute in whatever a can.

**Comment by persapiens** [comment]
Thanks @didiez  for your contribution and fast feedback also.

I is a pleasure to work in this "win-win" project.

I'll merge branch and release 1.5.1 next friday or sooner.
